//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>8</string>
  <string>15</string>
  <string>16</string>
  <string>13</string>
  <string>12</string>
  <string>4</string>
  <string>26</string>
  <string>17</string>
  <string>22</string>
  <string>9</string>
  <string>21</string>
  <string>24</string>
  <string>3</string>
  <string>23</string>
  <string>6</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultPalette {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultPalette"]));
            }
            set {
                this["DefaultPalette"] = value;
            }
        }
    }
}
